import { Metadata } from "next";
import "./style.scss";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: "Photos",
  description: "Generated by Oleksii Skrebtsov",
};

export default function PhotosLayout(props: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header/>
      {props.children}
    </>
  );
}