import { Metadata } from "next";
import "./style.scss";

export const metadata: Metadata = {
  title: "Photos",
  description: "Generated by Oleksii Skrebtsov",
};

export default function PhotosLayout(props: {
  children: React.ReactNode;
}) {
  return (
    <>
      <h1 className="photos-header">My Album</h1>
      {props.children}
    </>
  );
}