import type { Metadata } from "next";

import "./globals.css";
import styles from "./globals.module.scss";

export const metadata: Metadata = {
  title: "Album App",
  description: "Generated by Oleksii Skrebtsov",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={styles.appContainer}>
          {children}
        </div>
      </body>
    </html>
  );
}
