import { Header } from "@/components/header/header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Details",
  description: "Generated by Oleksii Skrebtsov",
};

export default function PhotosLayout(props: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header/>
      {props.children}
    </>
  );
}